# Generated by Django 6.0.3 on 2026-04-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatia", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="chat_background",
            field=models.CharField(default="chat-bg-light", max_length=30),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="chat_font",
            field=models.CharField(default="chat-font-normal", max_length=30),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_message_color",
            field=models.CharField(default="user-message-orange", max_length=30),
        ),
    ]
