# Generated by Django 6.0.3 on 2026-04-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatia", "0003_userprofile_chat_background_userprofile_chat_font_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="chat_font",
            field=models.CharField(default="chat-font-arial", max_length=30),
        ),
    ]
