# Generated by Django 6.0.3 on 2026-04-30 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatia", "0004_alter_userprofile_chat_font"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="chat_background",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="chat_font",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user_message_color",
        ),
    ]
