# Generated by Django 6.0.3 on 2026-05-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatia", "0005_remove_userprofile_chat_background_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user_message_background",
            field=models.CharField(default="user-bg-orange", max_length=30),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_message_font",
            field=models.CharField(default="user-font-arial", max_length=30),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_message_text_color",
            field=models.CharField(default="user-text-black", max_length=30),
        ),
    ]
