# Generated by Django 6.0.3 on 2026-05-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatia", "0006_userprofile_user_message_background_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="ai_message_background",
            field=models.CharField(default="ai-bg-yellow", max_length=30),
        ),
    ]
